name: CrossMix-OS Release

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

on:
  push:
    tags:
      - v*

jobs:
  tagged-release:
    name: Tagged release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get version
        run: |
          TAG="${{ github.ref_name }}"
          echo "BUILD_VERSION=${TAG#v}" >> $GITHUB_ENV
      - name: Install 7-Zip
        run: |
          mkdir -p /home/runner/work/CrossMix-OS/tools
          wget https://www.7-zip.org/a/7z2406-linux-x64.tar.xz -P /home/runner/work/CrossMix-OS/tools
          tar xvf /home/runner/work/CrossMix-OS/tools/7z2406-linux-x64.tar.xz -C /home/runner/work/CrossMix-OS/tools
          sudo cp /home/runner/work/CrossMix-OS/tools/7zz /usr/local/bin/
      - name: Extract RetroArch cores
        run: |
          find /home/runner/work/CrossMix-OS/CrossMix-OS/RetroArch/.retroarch/cores -name "*.7z" -execdir 7zz x {} \; -execdir rm {} \;
      - name: Cleaning image...
        run: |
          find /home/runner/work/CrossMix-OS/CrossMix-OS -type f -name ".gitkeep" -delete
          rm -rf /home/runner/work/CrossMix-OS/CrossMix-OS/_assets
          rm /home/runner/work/CrossMix-OS/CrossMix-OS/LICENSE
          rm /home/runner/work/CrossMix-OS/CrossMix-OS/README.md
          ls -la /home/runner/work/CrossMix-OS/CrossMix-OS
          rm -rf /home/runner/work/CrossMix-OS/CrossMix-OS/.git
          rm -rf /home/runner/work/CrossMix-OS/CrossMix-OS/.github
          ls -la /home/runner/work/CrossMix-OS/CrossMix-OS
          cd /home/runner/work/CrossMix-OS/CrossMix-OS
          /usr/local/bin/7zz a RetroArch/default_config.7z RetroArch/retroarch.cfg RetroArch/.retroarch/config/*
      - name: Create unified build
        run: |
          shopt -s dotglob
          cd /home/runner/work/CrossMix-OS/CrossMix-OS
          
          echo "Creating unified CrossMix-OS build compatible with both TSP and Brick devices..."
          
          # Keep all boot logo images for device adaptation
          echo "Keeping all boot logo resolutions for device compatibility..."
          
          # Keep all emulators and features (both devices have same hardware capabilities)
          echo "Including all emulators and features for universal compatibility..."
          
          # Create unified build with all features
          zip -r "/home/runner/work/CrossMix-OS/CrossMix-OS_v${{ env.BUILD_VERSION }}.zip" ./*
          
          echo "Unified build created: CrossMix-OS_v${{ env.BUILD_VERSION }}.zip"
          ls -lh "/home/runner/work/CrossMix-OS/CrossMix-OS_v${{ env.BUILD_VERSION }}.zip"
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: "CrossMix-OS v${{ env.BUILD_VERSION }}"
          prerelease: false
          files: |
            /home/runner/work/CrossMix-OS/CrossMix-OS_v${{ env.BUILD_VERSION }}.zip
          draft: true
          body: |
            ## CrossMix-OS v${{ env.BUILD_VERSION }}
            
            ### 📦 Universal Download
            - **Unified Build**: `CrossMix-OS_v${{ env.BUILD_VERSION }}.zip`
            - **Compatible with**: Both TrimUI Smart Pro (1280x720) and TrimUI Brick (1024x768)
            - **Full Features**: All emulators, PortMaster, and RetroArch cores included
            - **Device Adaptive**: Boot logos automatically match your device resolution
            
            ### 🎮 Device Compatibility
            This single build works on both devices since they share identical hardware capabilities:
            - **TrimUI Smart Pro**: Full experience with all features
            - **TrimUI Brick**: Full experience with all features
            - **Automatic Detection**: Device-specific optimizations applied at runtime
            
            ### 🔄 OTA Update Support
            The OTA system will automatically download and install the appropriate build for your device.
