name: CrossMix-OS Release

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

on:
  push:
    tags:
      - v*

jobs:
  tagged-release:
    name: Tagged release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get version
        run: |
          TAG="${{ github.ref_name }}"
          echo "BUILD_VERSION=${TAG#v}" >> $GITHUB_ENV
      - name: Install 7-Zip
        run: |
          mkdir -p /home/runner/work/CrossMix-OS/tools
          wget https://www.7-zip.org/a/7z2406-linux-x64.tar.xz -P /home/runner/work/CrossMix-OS/tools
          tar xvf /home/runner/work/CrossMix-OS/tools/7z2406-linux-x64.tar.xz -C /home/runner/work/CrossMix-OS/tools
          sudo cp /home/runner/work/CrossMix-OS/tools/7zz /usr/local/bin/
      - name: Extract RetroArch cores
        run: |
          find /home/runner/work/CrossMix-OS/CrossMix-OS/RetroArch/.retroarch/cores -name "*.7z" -execdir 7zz x {} \; -execdir rm {} \;
      - name: Cleaning image...
        run: |
          find /home/runner/work/CrossMix-OS/CrossMix-OS -type f -name ".gitkeep" -delete
          rm -rf /home/runner/work/CrossMix-OS/CrossMix-OS/_assets
          rm /home/runner/work/CrossMix-OS/CrossMix-OS/LICENSE
          rm /home/runner/work/CrossMix-OS/CrossMix-OS/README.md
          ls -la /home/runner/work/CrossMix-OS/CrossMix-OS
          rm -rf /home/runner/work/CrossMix-OS/CrossMix-OS/.git
          rm -rf /home/runner/work/CrossMix-OS/CrossMix-OS/.github
          ls -la /home/runner/work/CrossMix-OS/CrossMix-OS
          cd /home/runner/work/CrossMix-OS/CrossMix-OS
          /usr/local/bin/7zz a RetroArch/default_config.7z RetroArch/retroarch.cfg RetroArch/.retroarch/config/*
      - name: Create device-specific builds
        run: |
          shopt -s dotglob
          cd /home/runner/work/CrossMix-OS/CrossMix-OS
          
          # Create TSP (TrimUI Smart Pro) build - 1280x720
          echo "Creating TSP (1280x720) build..."
          # Remove legacy boot logo images to save space
          rm -rf Apps/BootLogo/Images_1024x768
          # Create device identifier file for TSP
          mkdir -p etc
          echo "tsp" > etc/trimui_device.txt
          zip -r "/home/runner/work/CrossMix-OS/CrossMix-OS_v${{ env.BUILD_VERSION }}_TSP.zip" ./*
          
          # Restore legacy images and create Legacy build - 1024x768  
          echo "Creating Legacy (1024x768) build..."
          git checkout HEAD -- Apps/BootLogo/Images_1024x768
          # Remove TSP boot logo images to save space
          rm -rf Apps/BootLogo/Images_1280x720
          # Create device identifier file for legacy devices
          echo "legacy" > etc/trimui_device.txt  
          zip -r "/home/runner/work/CrossMix-OS/CrossMix-OS_v${{ env.BUILD_VERSION }}_Legacy.zip" ./*
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: "CrossMix-OS v${{ env.BUILD_VERSION }}"
          prerelease: false
          files: |
            /home/runner/work/CrossMix-OS/CrossMix-OS_v${{ env.BUILD_VERSION }}_TSP.zip
            /home/runner/work/CrossMix-OS/CrossMix-OS_v${{ env.BUILD_VERSION }}_Legacy.zip
          draft: true
          body: |
            ## CrossMix-OS v${{ env.BUILD_VERSION }}
            
            ### 📦 Device-Specific Downloads
            - **TSP Build** (TrimUI Smart Pro - 1280x720): `CrossMix-OS_v${{ env.BUILD_VERSION }}_TSP.zip`
            - **Legacy Build** (Other devices - 1024x768): `CrossMix-OS_v${{ env.BUILD_VERSION }}_Legacy.zip`
            
            ### 🔄 OTA Update Support
            The device will automatically detect and download the appropriate build for your device.
