name: CrossMix-OS Canary Release

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  canary-release:
    name: Unified Canary release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip canary]')"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get version and build info
        run: |
          # Get the latest stable version from upstream repo
          LATEST_TAG=$(curl -s https://api.github.com/repos/cizia64/CrossMix-OS/releases/latest | jq -r '.tag_name' || echo "v1.3.0")
          BASE_VERSION=${LATEST_TAG#v}
          
          # Create canary version with short commit hash and timestamp
          SHORT_SHA=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date +%Y%m%d-%H%M)
          CANARY_VERSION="${BASE_VERSION}-canary.${TIMESTAMP}.${SHORT_SHA}"
          
          echo "BASE_VERSION=${BASE_VERSION}" >> $GITHUB_ENV
          echo "CANARY_VERSION=${CANARY_VERSION}" >> $GITHUB_ENV
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV
          echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV
          
          echo "Building unified canary version: ${CANARY_VERSION}"
      
      - name: Install 7-Zip
        run: |
          mkdir -p /home/runner/work/CrossMix-OS/tools
          wget https://www.7-zip.org/a/7z2406-linux-x64.tar.xz -P /home/runner/work/CrossMix-OS/tools
          tar xvf /home/runner/work/CrossMix-OS/tools/7z2406-linux-x64.tar.xz -C /home/runner/work/CrossMix-OS/tools
          sudo cp /home/runner/work/CrossMix-OS/tools/7zz /usr/local/bin/
      
      - name: Update version file for canary
        run: |
          echo "${CANARY_VERSION}" > /home/runner/work/CrossMix-OS/CrossMix-OS/System/usr/trimui/crossmix-version.txt
          
      - name: Extract RetroArch cores
        run: |
          find /home/runner/work/CrossMix-OS/CrossMix-OS/RetroArch/.retroarch/cores -name "*.7z" -execdir 7zz x {} \; -execdir rm {} \;
      
      - name: Prepare unified build
        run: |
          find /home/runner/work/CrossMix-OS/CrossMix-OS -type f -name ".gitkeep" -delete
          rm -rf /home/runner/work/CrossMix-OS/CrossMix-OS/_assets
          rm /home/runner/work/CrossMix-OS/CrossMix-OS/LICENSE
          rm /home/runner/work/CrossMix-OS/CrossMix-OS/README.md
          rm -rf /home/runner/work/CrossMix-OS/CrossMix-OS/.git
          rm -rf /home/runner/work/CrossMix-OS/CrossMix-OS/.github
          cd /home/runner/work/CrossMix-OS/CrossMix-OS
          /usr/local/bin/7zz a RetroArch/default_config.7z RetroArch/retroarch.cfg RetroArch/.retroarch/config/*
      
      - name: Create unified build in parts
        run: |
          shopt -s dotglob
          cd /home/runner/work/CrossMix-OS/CrossMix-OS
          echo "Creating unified CrossMix-OS build with full features in multiple parts..."
          
          # Split build into manageable parts to avoid 2GB limit
          echo "Creating Part 1: Core system, apps, and basic emulators..."
          zip -r "/home/runner/work/CrossMix-OS/CrossMix-OS_v${{ env.CANARY_VERSION }}_Part1.zip" \
            System Apps Emus BIOS Themes Icons Backgrounds trimui \
            --exclude="Apps/PortMaster/*" \
            --exclude="Emus/SCUMMVM/*" \
            --exclude="Emus/PSP/*"
          
          echo "Creating Part 2: Heavy components and RetroArch..."
          zip -r "/home/runner/work/CrossMix-OS/CrossMix-OS_v${{ env.CANARY_VERSION }}_Part2.zip" \
            RetroArch Apps/PortMaster Emus/SCUMMVM Emus/PSP \
            Pictures Data autorun.inf .VolumeIcon.icns
          
          # Create installation script
          cat > "/home/runner/work/CrossMix-OS/install.sh" << 'EOF'
          #!/bin/sh
          echo "CrossMix-OS Unified Installation Script"
          echo "======================================="
          echo "Compatible with both TrimUI Smart Pro and TrimUI Brick"
          echo ""
          
          # Find Part1 and Part2 files using ls with wildcards
          PART1_FILE=$(ls CrossMix-OS_v*_Part1.zip 2>/dev/null | head -1)
          PART2_FILE=$(ls CrossMix-OS_v*_Part2.zip 2>/dev/null | head -1)
          
          # Check if both parts are present
          if [ -z "$PART1_FILE" ] || [ -z "$PART2_FILE" ]; then
            echo "Error: Both part files must be present in the same directory"
            echo "Required files:"
            echo "- CrossMix-OS_v*_Part1.zip"
            echo "- CrossMix-OS_v*_Part2.zip"
            echo ""
            echo "Found files:"
            ls -1 CrossMix-OS_v*.zip 2>/dev/null || echo "  No CrossMix-OS files found"
            exit 1
          fi
          
          echo "Found files:"
          echo "  $PART1_FILE"
          echo "  $PART2_FILE"
          echo ""
          
          echo "Extracting Part 1 (Core system)..."
          unzip -q "$PART1_FILE"
          
          echo "Extracting Part 2 (Heavy components)..."
          unzip -q "$PART2_FILE"
          
          echo ""
          echo "Installation complete!"
          echo "You can now copy the extracted files to your TrimUI device SD card."
          echo ""
          echo "Device Detection:"
          echo "- Boot logos will automatically adapt to your device screen resolution"
          echo "- All emulators and features work on both TSP and Brick devices"
          echo ""
          echo "Remember to backup your existing installation first!"
          EOF
          
          echo "Unified build size information:"
          ls -lh /home/runner/work/CrossMix-OS/CrossMix-OS_v${{ env.CANARY_VERSION }}_Part*.zip
      
      - name: Delete previous canary releases
        run: |
          # Delete previous canary releases to avoid cluttering (keep latest 5)
          gh release list --limit 50 --repo ${{ github.repository }} | grep -E "v.*-canary\." | tail -n +6 | while read -r line; do
            tag=$(echo "$line" | awk '{print $1}')
            echo "Deleting old canary release: $tag"
            gh release delete "$tag" --yes --repo ${{ github.repository }} || true
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Unified Canary Release
        run: |
          # Create release using GitHub CLI with unified multi-part files
          gh release create "v${{ env.CANARY_VERSION }}" \
            --repo ${{ github.repository }} \
            --title "CrossMix-OS v${{ env.CANARY_VERSION }} (Canary)" \
            --notes "## 🚧 Unified Canary Release - v${{ env.CANARY_VERSION }}

          **⚠️ This is an automated pre-release build compatible with both TrimUI Smart Pro and TrimUI Brick devices.**

          - **Commit:** ${{ github.sha }}
          - **Branch:** ${{ github.ref_name }}
          - **Build Date:** ${{ env.TIMESTAMP }}
          - **Base Version:** ${{ env.BASE_VERSION }}

          ### 📦 Universal Build Features
          - **Full-featured build** with all emulators (SCUMMVM, PSP, DC, Saturn, NDS)
          - **PortMaster** for ports and games
          - **All RetroArch cores** (MAME2015, ScummVM, etc.)
          - **Device-adaptive assets** (boot logos automatically match your device resolution)
          - **Universal compatibility** - same build works on both TSP (1280x720) and Brick (1024x768)

          ### 💾 Installation Instructions
          This build is split into multiple parts to avoid GitHub's 2GB file size limit:

          1. **Download all files:**
             - \`CrossMix-OS_v${{ env.CANARY_VERSION }}_Part1.zip\` (Core system)
             - \`CrossMix-OS_v${{ env.CANARY_VERSION }}_Part2.zip\` (Heavy components)
             - \`install.sh\` (Installation script)

          2. **Install:**
             - Place all files in the same directory
             - Run: \`bash install.sh\`
             - Copy extracted files to your TrimUI device SD card

          ### 🎮 Device Compatibility
          - **TrimUI Smart Pro**: Full experience with all features
          - **TrimUI Brick**: Full experience with all features
          - **Automatic detection**: Boot logos and UI adapt to your device automatically

          ### 📋 Recent Changes
          ${{ github.event.head_commit.message }}

          ### ⚠️ Important Notes
          - **Download ALL parts** for complete installation
          - This is a **development build** and may contain bugs
          - Use at your own risk - always backup your device first
          - Report issues on the [GitHub Issues](https://github.com/cizia64/CrossMix-OS/issues) page

          ### 🔄 OTA Update Support
          The OTA system will automatically download the appropriate build for your device." \
            --prerelease \
            "/home/runner/work/CrossMix-OS/CrossMix-OS_v${{ env.CANARY_VERSION }}_Part1.zip" \
            "/home/runner/work/CrossMix-OS/CrossMix-OS_v${{ env.CANARY_VERSION }}_Part2.zip" \
            "/home/runner/work/CrossMix-OS/install.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}